tabWidth: 2
useTabs: true
semi: true
singleQuote: false
quoteProps: as-needed
trailingComma: all
bracketSpacing: true
arrowParens: avoid
proseWrap: never
endOfLine: lf
embeddedLanguageFormatting: auto
